### ISSUE TITLE
Issue with ng2 and webpack

### ISSUE THREAD

**Issue by manijak** [manijak/nativescript-carousel#11]
Moved from another issue, created by @danielgek
-
@manijak tried to use your plugin with angular 2 and webpack(with AoT enabled, it works fine when i'm not using AoT) but it fails, i am not using it dynamically the problem is with webpack bundling i think
```
Angular is running in the development mode. Call enableProdMode() to enable the production mode.
JS: EXCEPTION: Uncaught (in promise): Error: Trying to link invalid 'this' to a Java object
JS: ORIGINAL STACKTRACE:
JS: Error: Uncaught (in promise): Error: Trying to link invalid 'this' to a Java object
JS:     at resolvePromise (file:///data/data/pt.minsaude.spms.ces/files/app/vendor.js:54038:31)
JS:     at resolvePromise (file:///data/data/pt.minsaude.spms.ces/files/app/vendor.js:54023:17)
JS:     at file:///data/data/pt.minsaude.spms.ces/files/app/vendor.js:54071:17
JS:     at ZoneDelegate.module.exports.ZoneDelegate.invokeTask (file:///data/data/pt.minsaude.spms.ces/files/app/vendor.js:53845:37)
JS:     at Object.onInvokeTask (file:///data/data/pt.minsaude.spms.ces/files/app/vendor.js:19206:37)
JS:     at ZoneDelegate.module.exports.ZoneDelegate.invokeTask (file:///data/data/pt.minsaude.spms.ces/files/app/vendor.js:53844:42)
JS:     at Zone.module.exports.Zone.runTask (file:///data/data/pt.minsaude.spms.ces/files/app/vendor.js:53745:47)
JS:     at drainMicroTaskQueue (file:///data/data/pt.minsaude.spms.ces/files/app/vendor.js:53977:35)
JS: Unhandled Promise rejection: Trying to link invalid 'this' to a Java object ; Zone: angular ; Task: Promise.then ; Value: Error: Trying to link invalid 'this' to a Java object Error: Trying to link invalid 'this' to a Java object
JS:     at new CarouselPagerAdapterClassInner (file:///data/data/pt.minsaude.spms.ces/files/app/bundle.js:32016:20)
JS:     at Carousel.module.exports.Carousel._createUI (file:///data/data/pt.minsaude.spms.ces/files/app/bundle.js:31717:36)
JS:     at Carousel.module.exports.View._onContextChanged (file:///data/data/pt.minsaude.spms.ces/files/app/vendor.js:1307:14)
JS:     at Carousel.module.exports.View._onAttached (file:///data/data/pt.minsaude.spms.ces/files/app/vendor.js:1258:14)
JS:     at eachChild (file:///data/data/pt.minsaude.spms.ces/files/app/vendor.js:1263:23)
JS:     at GridLayout.module.exports.LayoutBase._eachChildView (file:///data/data/pt.minsaude.spms.ces/files/app/vendor.js:80321:22)
JS:     at GridLayout.module.exports.View._onAttached (file:///data/data/pt.minsaude.spms.ces/files/app/vendor.js:1270:18)
JS:     at eachChild (file:///data/data/pt.minsaude.spms.ces/files/app/vendor.js:1263:23)
JS:     at ProxyViewContainer.module.exports.LayoutBase._eachChildView (file:///data/data/pt.minsaude.spms.ces/files/app/vendor.js:80321:22)
JS:     at ProxyViewContainer.module.exports.View._onAttached (file:///data/data/pt.minsaude.spms.ces/files/app/vendor.js:1270:18)
JS: Error: Uncaught (in promise): Error: Trying to link invalid 'this' to a Java object

```

 i found a similar issue on [other plugin](https://github.com/PeterStaev/NativeScript-Drop-Down/issues/35), but the fix is related with typescript and you are not using typescript, any suggestions ? do you wan't me to open another separated issue ?

**Comment by danielgek** [comment]
@manijak sorry for not posting in a new issue right way

**Comment by manijak** [comment]
no problem @danielgek ! 
I just published a new version to npm, 2.3.1. Includes a potential fix for your issue. Please give it a go and report back :) 

Would be wise to clean the platform prior to upgrade of the plugin. Thanks.

**Comment by danielgek** [comment]
I test it latter can't right now and thanks that was fast  :P

**Comment by danielgek** [comment]
It's working well now, Thank you ;)

**Comment by manijak** [comment]
Great stuff! Thanks for testing.
