### ISSUE TITLE
"ReferenceError: Can't find variable: DKCarouselView"

### ISSUE THREAD

**Issue by sucre101** [manijak/nativescript-carousel#174]
In iOS device:
CONSOLE ERROR file:///app/tns_modules/nativescript-vue/dist/index.js:2133:20: [Vue warn]: Error in nextTick: "ReferenceError: Can't find variable: DKCarouselView"
2020-10-29 18:23:26.123 nsplaydev[1410:249923] PlayLiveSync: Successfully sent log message 48ySB8U4i
2020-10-29 18:23:26.123 nsplaydev[1410:249923] PlayLiveSync: Successfully sent log message 48ySB8U4i
2020-10-29 18:23:26.123 nsplaydev[1410:249923] PlayLiveSync: Successfully sent log message 48ySB8U4i
2020-10-29 18:23:26.123 nsplaydev[1410:249923] PlayLiveSync: Successfully sent log message 48ySB8U4i
2020-10-29 18:23:26.123 nsplaydev[1410:249923] PlayLiveSync: Successfully sent log message 48ySB8U4i
2020-10-29 18:23:26.123 nsplaydev[1410:249923] PlayLiveSync: Successfully sent log message 48ySB8U4i
2020-10-29 18:23:26.135 nsplaydev[1410:249923] ***** Fatal JavaScript exception - application has been terminated. *****
2020-10-29 18:23:26.135 nsplaydev[1410:249923] Native stack trace:
1   0x100fca928 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x10100502c NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
3   0x101b727f8 ffi_closure_SYSV_inner
4   0x101b741b4 .Ldo_closure
5   0x25b9182d8 <redacted>
6   0x2331d0c60 <redacted>
7   0x2331d5c08 <redacted>
8   0x2331383e4 <redacted>
9   0x233166620 <redacted>
10  0x23316715c <redacted>
11  0x22ec244fc <redacted>
12  0x22ec1f224 <redacted>
13  0x22ec1f7a0 <redacted>
14  0x22ec1efb4 CFRunLoopRunSpecific
15  0x230e2079c GSEventRunModal
16  0x25b480c38 UIApplicationMain
17  0x101b74044 ffi_call_SYSV
18  0x101b71f1c ffi_call_int
19  0x101b71a18 ffi_call
20  0x100f8d46c NativeScript::FunctionWrapper::call(JSC::ExecState*)
21  0x101b3ecf0 llint_entry
22  0x101b3c108 llint_entry
23  0x101b3c108 llint_entry
24  0x101b3c108 llint_entry
25  0x101b3c108 llint_entry
26  0x101b3c108 llint_entry
27  0x101b3c108 llint_entry
28  0x101b3c060 llint_entry
29  0x101b3c108 llint_entry
30  0x101b1d7c8 vmEntryToJavaScript

Guys, how to resolve this problem ?

**Comment by manijak** [comment]
Provide more info please. What version of Carousel plugin are you using and platform/core-modules version as well.

**Comment by VincenzoAsciolla** [comment]
I'm facing the same error, the following are my Angular project's dependencies:

"dependencies": {
    "@angular/animations": "~11.2.7",
    "@angular/common": "~11.2.7",
    "@angular/compiler": "~11.2.7",
    **"@angular/core": "~11.2.7",**
    "@angular/forms": "~11.2.7",
    "@angular/platform-browser": "~11.2.7",
    "@angular/platform-browser-dynamic": "~11.2.7",
    "@angular/router": "~11.2.7",
    "@nativescript/angular": "~11.8.0",
    **"@nativescript/core": "~8.0.0",**
    "@nativescript/imagepicker": "~1.0.3",
    "@nativescript/theme": "~3.0.1",
    "@ngrx/effects": "^12.0.0",
    "@ngrx/store": "^12.0.0",
    "@ngrx/store-devtools": "^12.1.0",
    "@nstudio/nativescript-cardview": "^2.0.1",
    **"nativescript-carousel": "^7.0.1",**
    "nativescript-ngx-fonticon": "^7.0.0",
    "nativescript-ui-listview": "~9.1.0",
    "nativescript-videoplayer": "^5.0.1",
    "ngrx-devtools-nativescript": "^7.0.0",
    "reflect-metadata": "~0.1.13",
    "rxjs": "~6.6.7",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~11.2.7",
    "@nativescript/android": "8.0.0",
    "@nativescript/ios": "8.0.0",
    "@nativescript/types": "~8.0.0",
    "@nativescript/webpack": "beta",
    "@ngtools/webpack": "~11.2.6",
    "typescript": "~4.0.0"
  },

The error is the following and it is thrown as my app try to instantiate the nativescript carousel on iOS v13.6:

2021-08-18 12:28:02.674 nsplaydev[405:26747] Native stack trace:
1   0x10130e348 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x101348434 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
3   0x101eb3388 ffi_closure_SYSV_inner
4   0x101eb41b4 .Ldo_closure
5   0x1a1ed1b7c <redacted>
6   0x1a1ed222c <redacted>
7   0x1a1e28454 <redacted>
8   0x1a1e3c87c <redacted>
9   0x1a1e3dc1c <redacted>
10  0x1a1e20900 <redacted>
11  0x1a2a0b2bc <redacted>
12  0x1a505c978 <redacted>
13  0x1a505cdb8 <redacted>
14  0x1a506f21c <redacted>
15  0x1a4fb3e10 <redacted>
16  0x1a4fde8c4 <redacted>
17  0x1a4fdf4b4 <redacted>
18  0x19e38c11c <redacted>
19  0x19e386e4c <redacted>
20  0x19e3872dc <redacted>
21  0x19e386bc8 CFRunLoopRunSpecific
22  0x1a87685cc GSEventRunModal
23  0x1a2539744 UIApplicationMain
24  0x101eb4044 ffi_call_SYSV
25  0x101eb2ae8 ffi_call_int
26  0x101eb2648 ffi_call
27  0x1012d13d8 NativeScript::FunctionWrapper::call(JSC::ExecState*)
28  0x101e7fb10 llint_entry
29  0x101e7cf28 llint_entry
30  0x101e7cf28 llint_entry
31  0x101e7cf28 llint_entry
2021-08-18 12:28:02.676 nsplaydev[405:26747] JavaScript stack trace:
2021-08-18 12:28:02.676 nsplaydev[405:26747] createNativeView(file:///app/vendor.js:162739:41)
at _setupUI(file:///app/vendor.js:120840:47)
at file:///app/vendor.js:120853:27
at eachChildView(file:///app/vendor.js:131498:36)
at eachChild(file:///app/vendor.js:122818:27)
at _setupUI(file:///app/vendor.js:120852:23)
at file:///app/vendor.js:120853:27
at eachChildView(file:///app/vendor.js:131498:36)
at eachChild(file:///app/vendor.js:122818:27)
at _setupUI(file:///app/vendor.js:120852:23)
at file:///app/vendor.js:120853:27
at eachChildView(file:///app/vendor.js:131498:36)
at eachChild(file:///app/vendor.js:122818:27)
at _setupUI(file:///app/vendor.js:120852:23)
at file:///app/vendor.js:120853:27
at eachChildView(file:///app/vendor.js:131498:36)
at eachChild(file:///app/vendor.js:122818:27)
at _setupUI(file:///app/vendor.js:120852:23)
at file:///app/vendor.js:120853:27
at eachChildView(file:///app/vendor.js:118263:21)
at eachChild(file:///app/vendor.js:122818:27)
at _setupUI(file:///app/vendor.js:120852:23)
at file:///app/vendor.js:120853:27
at eachChildView(file:///app/vendor.js:131498:36)
at eachChild(file:///app/vendor.js:122818:27)
at _setupUI(file:///app/vendor.js:120852:23)
at file:///app/vendor.js:120853:27
at eachChildView(file:///app/vendor.js:118263:21)
at eachChildView(file:///app/vendor.js:134107:28)
at eachChild(file:///app/vendor.js:122818:27)
at _setupUI(file:///app/vendor.js:120852:23)
at _addViewCore(file:///app/vendor.js:120736:26)
at _addView(file:///app/vendor.js:120725:26)
at file:///app/vendor.js:133548:31
at UIApplicationMain([native code])
at run(file:///app/vendor.js:101521:26)
at bootstrapNativeScriptApp(file:///app/vendor.js:95047:73)
at bootstrapApp(file:///app/vendor.js:94938:38)
at bootstrapModule(file:///app/vendor.js:94919:26)
at ./src/main.ts(file:///app/bundle.js:39:101)
at __webpack_require__(file:///app/runtime.js:28:37)
at __webpack_exec__(file:///app/bundle.js:1676:58)
at file:///app/bundle.js:1677:159
at file:///app/runtime.js:141:23
at file:///app/bundle.js:1677:48
at anonymous(file:///app/bundle.js:1682:3)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
2021-08-18 12:28:02.676 nsplaydev[405:26747] JavaScript error:
file:///app/vendor.js:162739:41: JS ERROR ReferenceError: Can't find variable: DKCarouselView
2021-08-18 12:28:02.676 nsplaydev[405:26747] PlayLiveSync: Uncaught Exception
2021-08-18 12:28:02.678 nsplaydev[405:26747] PlayLiveSync: Sending crash report
2021-08-18 12:28:06.679 nsplaydev[405:26747] *** JavaScript call stack:
(
        0   UIApplicationMain@[native code]
        1   run@file:///app/vendor.js:101521:26
        2   bootstrapNativeScriptApp@file:///app/vendor.js:95047:73
        3   bootstrapApp@file:///app/vendor.js:94938:38
        4   bootstrapModule@file:///app/vendor.js:94919:26
        5   ./src/main.ts@file:///app/bundle.js:39:101
        6   __webpack_require__@file:///app/runtime.js:28:37
        7   __webpack_exec__@file:///app/bundle.js:1676:58
        8   @file:///app/bundle.js:1677:159
        9   @file:///app/runtime.js:141:23
        10  @file:///app/bundle.js:1677:48
        11  anonymous@file:///app/bundle.js:1682:3
        12  evaluate@[native code]
        13  moduleEvaluation@:1:11
        14  @:2:1
        15  asyncFunctionResume@:1:11
        16  @:24:9
        17  promiseReactionJob@:1:11
)
2021-08-18 12:28:06.680 nsplaydev[405:26747] *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: ReferenceError: Can't find variable: DKCarouselView
 at 
createNativeView(file:///app/vendor.js:162739:41)
at _setupUI(file:///app/vendor.js:120840:47)
at file:///app/vendor.js:120853:27
at eachChildView(file:///app/vendor.js:131498:36)
at eachChild(file:///app/vendor.js:122818:27)
at _setupUI(file:///app/vendor.js:120852:23)
at file:///app/vendor.js:120853:27
at eachChildView(file:///app/vendor.js:131498:36)
at eachChild(file:///app/vendor.js:122818:27)
at _setupUI(file:///app/vendor.js:120852:23)
at file:///app/vendor.js:120853:27
at eachChildView(file:///app/vendor.js:131498:36)
at eachChild(file:///app/vendor.js:122818:27)
at _setupUI(file:///app/vendor.js:120852:23)
at file:///app/vendor.js:120853:27
at eachChildView(file:///app/vendor.js:131498:36)
at eachChild(file:///app/vendor.js:122818:27)
at _setupUI(file:///app/vendor.js:120852:23)
at file:///app/vendor.js:120853:27
at eachChildView(file:///app/vendor.js:118263:21)
at eachChild(file:///app/vendor.js:122818:27)
at _setupUI(file:///app/vendor.js:120852:23)
at file:///app/vendor.js:120853:27
at eachChildView(file:///app/vendor.js:131498:36)
at eachChild(file:///app/vendor.js:122818:27)
at _setupUI(file:///app/vendor.js:120852:23)
at file:///app/vendor.js:120853:27
at eachChildView(file:///app/vendor.js:118263:21)
at eachChildView(file:///app/vendor.js:134107:28)
at eachChild(file:///app/vendor.js:122818:27)
at _setupUI(file:///app/vendor.js:120852:23)
at _addViewCore(file:///app/vendor.js:120736:26)
at _addView(file:///app/vendor.js:120725:26)
at file:///app/vendor.js:133548:31
at UIApplicationMain([native code])
at run(file:///app/vendor.js:101521:26)
at bootstrapNativeScriptApp(file:///app/vendor.js:95047:73)
at bootstrapApp(file:///app/vendor.js:94938:38)
at bootstrapModule(file:///app/vendor.js:94919:26)
at ./src/main.ts(file:///app/bundle.js:39:101)
at __webpack_require__(file:///app/runtime.js:28:37)
at __webpack_exec__(file:///app/bundle.js:1676:58)
at file:///app/bundle.js:1677:159
at file:///app/runtime.js:141:23
at file:///app/bundle.js:1677:48
at anonymous(file:///app/bundle.js:1682:3)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
', reason: '(null)'
*** First throw call stack:
(0x19e411344 0x19e126cc0 0x10130e820 0x101348434 0x101eb3388 0x101eb41b4 0x1a1ed1b7c 0x1a1ed222c 0x1a1e28454 0x1a1e3c87c 0x1a1e3dc1c 0x1a1e20900 0x1a2a0b2bc 0x1a505c978 0x1a505cdb8 0x1a506f21c 0x1a4fb3e10 0x1a4fde8c4 0x1a4fdf4b4 0x19e38c11c 0x19e386e4c 0x19e3872dc 0x19e386bc8 0x1a87685cc 0x1a2539744 0x101eb4044 0x101eb2ae8 0x101eb2648 0x1012d13d8 0x101e7fb10 0x101e7cf28 0x101e7cf28 0x101e7cf28 0x101e7cf28 0x101e7cf28 0x101e7cf28 0x101e7ce80 0x101e7cf28 0x101e7cf28 0x101e7cf28 0x101e7cf28 0x101e5e5e8 0x10140ce48 0x101cb0cb4 0x1012e98f4 0x101b819d0 0x101e7f7cc 0x101e7cf28 0x101e7cf28 0x101e7cf28 0x101e7ce80 0x101e7cf28 0x101e5e5e8 0x10140ce48 0x101cb0e50 0x101b7ad9c 0x1012df304 0x101358350 0x10113625c 0x1007b7524 0x19e203384)
libc++abi.dylib: terminating with uncaught exception of type NSException
2021-08-18 12:28:06.680 nsplaydev[405:26747] PlayLiveSync: Uncaught Exception

Do you know why? Thanks

**Comment by narender56** [comment]
Update your POD file with this and delete platforms and restart

> pod 'DKCarouselView', :git => 'https://github.com/manijak/DKCarouselView', :tag => '2.4.15'
