### ISSUE TITLE
Cannot read property 'PageIndicatorView

### ISSUE THREAD

**Issue by KhaiKing** [manijak/nativescript-carousel#31]
![image](https://cloud.githubusercontent.com/assets/29058585/26575003/be07ede4-454d-11e7-9c4e-8d78971d6142.png)

**Comment by manijak** [comment]
You will not get a lot of help posting issues like this. 
Please provide more info as to how & what you did to get this error. 

Thanks

**Comment by KhaiKing** [comment]
That is your demo code. i only run it and error.
PS: more 1 error when i add your plugin and  build.
![image](https://cloud.githubusercontent.com/assets/29058585/26590815/dabf8d4c-4585-11e7-9ecc-2c1eba3fe0e4.png)

**Comment by manijak** [comment]
Thanks for the info. The demo works fine, just ran a test on it.
It's good that you have NativeScript 3.0.1, just make scure that also the plugin `nativescript-carousel` is also version 3.0.1 or higher. 

Regarding your last error, it looks like you do not have the latest SDK installed? The IndicatorView component for Android has following dependencies:
```
 com.android.support:support-annotations:25.3.0
 com.android.support:support-compat:25.3.0
 com.android.support:support-core-ui:25.3.0
```
From the looks of it, you do not have 25.3.0 installed.

**Comment by KhaiKing** [comment]
Haha. I test on Android 6 (API 23). OK Thank.

**Comment by luiscarbonell** [comment]
Running into a very similar problem...haven't found a fix yet...

Hoping to get some help on how to fix the issue...?

@KhaiKing @manijak 

**Running**

* Device: Galaxy S10e
* Android version: 9
* NativeScript version: 2.2.2

**Stack Trace**

```
LOG from device Galaxy S10e: An uncaught Exception occurred on "main" thread.
Calling js method onCreateView failed
TypeError: Cannot read property 'PageIndicatorView' of undefined

StackTrace:
Carousel.createNativeView(file:///data/data/org.nativescript.preview/files/app/vendor.js:784:42)
        at ViewBase._setupUI(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view-base/view-base.js:497:25)
        at (file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view-base/view-base.js:539:13)
        at LayoutBaseCommon.eachChildView(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/layouts/layout-base-common.js:125:20)
        at ViewCommon.eachChild(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view/view-common.js:885:10)
        at ViewBase._setupUI(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view-base/view-base.js:538:10)
        at (file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view-base/view-base.js:539:13)
        at ContentView.eachChildView(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/content-view/content-view.js:70:7)
        at PageBase.eachChildView(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/page/page-common.js:126:36)
        at ViewCommon.eachChild(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view/view-common.js:885:10)
        at ViewBase._setupUI(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view-base/view-base.js:538:10)
        at ViewBase._addViewCore(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view-base/view-base.js:437:12)
        at ViewBase._addView(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view-base/view-base.js:426:10)
        at FragmentCallbacksImplementation.onCreateView(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/frame/frame.js:700:13)
        at FragmentClass.onCreateView(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/frame/fragment.js:29:34)
        at com.tns.Runtime.callJSMethodNative(Native Method)
        at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
        at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
        at com.tns.Runtime.callJSMethod(Runtime.java:1160)
        at com.tns.Runtime.callJSMethod(Runtime.java:1138)
        at com.tns.Runtime.callJSMethod(Runtime.java:1134)
        at com.tns.FragmentClass.onCreateView(FragmentClass.java:54)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7032)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

**Code**

```javascript
// app.js
import Vue from "nativescript-vue";

// Use Carousel
Vue.registerElement(
    "Carousel",
    () => require("nativescript-carousel").Carousel
);
Vue.registerElement(
    "CarouselItem",
    () => require("nativescript-carousel").CarouselItem
);

// Use NativeScript Vue Navigator
import Navigator from "./nativescript-vue-navigator";
import { routes } from "./routes";
Vue.use(Navigator, { routes });

import App from "./App";

new Vue({
    render: h => h(App)
}).$start();
```

```vue
<!-- App.vue -->
<template>
    <Navigator defaultRoute="/welcome" />
</template>

<script>

export default {
    data() {
	    return {
	    };
    }
}
</script>

<style>
</style>
```

```vue
<!-- Main.vue -->
<template>
  <Page actionBarHidden="true">
    <RadSideDrawer
      ref="drawer"
      drawerLocation="Left"
      gesturesEnabled="true"
      :drawerTransition="transition"
    >
      <StackLayout ~drawerContent backgroundColor="gray">
        <StackLayout>
          <Label text="Navigation Menu" />
        </StackLayout>
        <StackLayout>
          <Label text="Welcome" padding="10" @tap="onRouteTap('/welcome')" />
          <Label text="Main" padding="10" @tap="onRouteTap('/main')" />
        </StackLayout>
        <Label
          text="Close"
          color="lightgray"
          padding="10"
          style="horizontal-align: center"
          @tap="onCloseDrawerTap"
        />
      </StackLayout>
      <Frame ~mainContent ref="drawerMainContent">
        <Page>
          <!-- Top Bar -->
          <ActionBar title="Main Page">
            <NavigationButton icon="res://menu" @tap="onOpenDrawerTap" />
            <StackLayout horizontalAlignment="center">
              <Label text="Main" style="font-weight: bold;" />
            </StackLayout>
          </ActionBar>
          <!-- END Top Bar -->

          <!-- Page Content -->
          <GridLayout class="carousel-layout-fix">
            <Carousel
              id="carousel"
              @pageChanged="myChangeEvent"
              ios:indicatorOffset="0,-30"
              ios:finite="true"
              ios:bounce="false"
              showIndicator="true"
              indicatorAnimation="SWAP"
              indicatorColor="#66ccff"
              indicatorColorUnselected="#cceeff"
              height="100%"
              width="100%"
              debug="true"
            >
              <CarouselItem id="slide1" verticalAlignment="middle">
                <Label
                  text="Each slide is defined in the XML."
                  textWrap="true"
                  margin="30"
                />
                <Label
                  text="Slide 1"
                  backgroundColor="#50000000"
                  horizontalAlignment="center"
                ></Label>

                <Label
                  text="Wrap the Carousel in a GridLayout in order to place the indicator on top (android)"
                  textWrap="true"
                  margin="30"
                  ios:visibility="collapsed"
                />
              </CarouselItem>

              <CarouselItem id="slide2" verticalAlignment="middle">
                <Label
                  text="'finite' is set to True. Carousel will stop at the last slide."
                  textWrap="true"
                  margin="30"
                  android:visibility="collapsed"
                />
                <Label
                  text="Indicator animation type: 'swap'"
                  textWrap="true"
                  ios:visibility="collapsed"
                  margin="30"
                />
                <Label
                  text="Slide 2"
                  backgroundColor="#50000000"
                  horizontalAlignment="center"
                ></Label>
              </CarouselItem>

              <CarouselItem id="slide3" verticalAlignment="middle">
                <Label
                  text="Carousel can be used in fullscreen, just set height to 100%"
                  textWrap="true"
                  margin="30"
                />
                <Label
                  text="Slide 3"
                  backgroundColor="#50000000"
                  horizontalAlignment="center"
                ></Label>
              </CarouselItem>

              <CarouselItem id="slide4" verticalAlignment="middle">
                <Label
                  text="Enjoy using the Carousel plugin :)"
                  textWrap="true"
                  margin="30"
                />
                <Label
                  text="Slide 4"
                  backgroundColor="#50000000"
                  horizontalAlignment="center"
                ></Label>
              </CarouselItem>
            </Carousel>
          </GridLayout>
          <!-- END Page Content -->
        </Page>
      </Frame>
    </RadSideDrawer>
  </Page>
</template>

<script>
const carousel = require("nativescript-carousel");
import { SlideInOnTopTransition } from "nativescript-ui-sidedrawer";

export default {
  methods: {
    onItemTap: function(args) {
      console.log("Item with index: " + args.index + " tapped");
    },

    onOpenDrawerTap() {
      this.$refs.drawer.nativeView.showDrawer();
    },
    onCloseDrawerTap() {
      this.$refs.drawer.nativeView.closeDrawer();
    },
    onRouteTap(route) {
      this.$navigator.navigate(route, {
        clearHistory: true
      });
    },
    onTextRecognitionResult() {
      console.log("onTextRecognitionResult");
    },
    myChangeEvent: function(args) {
      var changeEventText = "Page changed to index: " + args.index;
      console.log(changeEventText);
    }
  },
  created() {},
  data() {
    return {
      transition: new SlideInOnTopTransition(),
      message: "Fear not, young Skywalker"
    };
  }
};
</script>

<style scoped>
#slide1 {
  background: linear-gradient(45deg, #f06f7e, #f34a30);
  vertical-align: center;
}

#slide2 {
  background: linear-gradient(-45deg, #1d976c, #93f9b9);
  vertical-align: center;
}

#slide3 {
  background: linear-gradient(45deg, #1d2b64, #f8cdda);
  vertical-align: center;
}

#slide4 {
  background: linear-gradient(tobottom, #003973, #e5e5be);
  vertical-align: center;
}
.carousel-layout-fix {
  padding: 0.1 0;
  margin: -0.1 0;
}
</style>

```

**Comment by manijak** [comment]
Don’t know if it is a missprint or not but there is no way that this plugin will work on nativescript 2.2.2...

**Comment by luiscarbonell** [comment]
@manijak Sorry about that - just edited it!

It was **_6.2.2_**.

**Comment by luiscarbonell** [comment]
Also tried [Carousel Without Page Indicators](https://market.nativescript.org/plugins/nativescript-carousel-without-page-indicators) - but it throws the same error.

**Comment by narender56** [comment]
2023 and still same issue, not sure why chose to work this library
